# The purpose of this Antora playbook is to build the docs in the current branch.
antora:
  extensions:
    - require: '@springio/antora-extensions'
      root_component_name: 'vault'
site:
  title: Spring Vault
  url: https://docs.spring.io/spring-vault/reference
content:
  sources:
    - url: ./../../..
      branches: HEAD
      start_path: src/main/antora
      worktrees: true
asciidoc:
  attributes:
    page-stackoverflow-url: https://stackoverflow.com/tags/spring-vault
    page-related-doc-categories: security,cloud
    page-related-doc-projects: framework
    hide-uri-scheme: '@'
    tabs-sync-option: '@'
  extensions:
    - '@asciidoctor/tabs'
    - '@springio/asciidoctor-extensions'
    - '@springio/asciidoctor-extensions/javadoc-extension'
  sourcemap: true
urls:
  latest_version_segment: ''
runtime:
  log:
    failure_level: warn
    format: pretty
ui:
  bundle:
    url: https://github.com/spring-io/antora-ui-spring/releases/download/v0.4.16/ui-bundle.zip
    snapshot: true
